# Generated by Django 5.1.4 on 2024-12-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParserConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interval_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Interval in minutes for the parser to run",
                    ),
                ),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PDFFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("downloaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
